### ISSUE TITLE
Identity teaft when using multiple auth methods

### ISSUE THREAD

**Issue by muppeth** [punitkrjain/discourse-ldap-auth#1]
It if very easy to login as other person if the plugin is on and LDAP has open registration. All you need to do is to create an account on LDAP that exists on discourse instance (via other auth methods) but not on LDAP. 
In result you will be able to login and have full control over the persons account.
I tried the same with github auth and it is not possible as the discourse will indicate the account exists and will prompt you for new user registration with different username (usually adding 1 at the end).

**Comment by muppeth** [comment]
I noticed when stealing identity, that the email hasn't change (the original user email was still there rather then email on ldap). 
Maybe the idea would be to check against users email, and only when it matches allow authentication.

**Comment by muppeth** [comment]
THis plugin however does not allow that. If the email addresses do not match, it will prompt for new user creation. have a look:
https://github.com/jonmbake/discourse-ldap-auth

Also it let's you use any ldap uid (cn, sn, nick etc)

**Comment by punitkrjain** [comment]
I have fixed this with last commit. verification is now by email only.
